# Default values for rs-user-client-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  apiUrl: http://coprs.werum.de/prip/odata/v1/Products
  mapBackgrounds: |
    "[{\"name\": \"OpenStreetMap background map\",\"layers\":[{\"url\":\"https://tiles.esa.maps.eox.at/wms\",\"layerName\":\"osm_3857\"}]},
      {\"name\": \"Sentinel-2 cloudless 2018 background map\",\"layers\": [{\"url\": \"https://tiles.esa.maps.eox.at/wms\",\"layerName\": \"s2cloudless_3857\"}]},
      {\"name\": \"Terrain background map\",\"layers\": [{\"url\": \"https://tiles.esa.maps.eox.at/wms\",\"layerName\": \"terrain_3857\"}]}]"
  baseHref: /uwc/
  keycloak: |
    "{\"url\":\"http://coprs.werum.de/auth\",\"realm\":\"master\",\"clientId\": \"user-web-client\"}"
  mapView: |
    "{\"regionSelectionFillColor\":\"rgba(255,155,51,0.3)\",\"regionSelectionStrokeColor\":\"rgba(255,155,51,0.6)\",\"selectionFillColor\":\"rgba(0, 114, 163, 0.3)\",\"selectionStrokeColor\":\"rgba(0, 114, 163, 0.6)\",\"highlightFillColor\":\"rgba(50, 211, 63, 0.3)\",\"highlightStrokeColor\":\"rgba(50, 211, 63, 0.8)\"}"
  filterConfig: |
    "[{\"attributeName\":\"PublicationDate\",\"valueType\":\"date\"},{\"attributeName\":\"EvictionDate\",\"valueType\":\"date\"},{\"attributeName\":\"ContentDate/Start\",\"valueType\":\"date\"},{\"attributeName\":\"ContentDate/End\",\"valueType\":\"date\"},{\"attributeName\":\"ContentLength\",\"valueType\":\"size\"},{\"attributeName\":\"Name\",\"valueType\":\"string\"},{\"attributeName\":\"ProductType\",\"valueType\":\"string\"}]"
  additionalAttributes: |
    "[{\"label\":\"Orbit Number\", \"value\": \"orbitNumber\"}]"
image:
  # Overrides the image tag whose default is the chart appVersion.
  # use image from COPRS repository
  registry: artifactory.coprs.esa-copernicus.eu
  repository: rs-docker

  name: rs-user-web-client
  tag: {{CHART_VERSION}}

  imagePullSecrets: spring-cloud-dataflow-registry-dockersecret

  # use image from local computer
  #repository: rs-user-client
  #tag: dev # use image from local computer
  #pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
